# Generated by Django 5.2.8 on 2025-11-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_bust_post_hip_post_review_post_waist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
