# Generated by Django 4.2.25 on 2025-11-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(db_index=True, help_text='作品CID (ユニークID)', max_length=20, unique=True)),
                ('title', models.CharField(help_text='作品タイトル', max_length=255)),
                ('name', models.CharField(blank=True, help_text='出演者名 (probe由来)', max_length=100)),
                ('maker', models.CharField(blank=True, db_index=True, help_text='メーカー名', max_length=100)),
                ('label', models.CharField(blank=True, help_text='レーベル名', max_length=100)),
                ('sizes', models.CharField(blank=True, help_text='サイズ (T/B/W/H)', max_length=50)),
                ('genres', models.JSONField(blank=True, default=list, help_text='ジャンルのリスト')),
                ('review_body', models.TextField(blank=True, help_text='紹介文（レビュー本文）')),
                ('affiliate_url', models.URLField(blank=True, max_length=1024)),
                ('sample_movie_url', models.URLField(blank=True, max_length=1024)),
                ('draft_path', models.CharField(blank=True, help_text='元のMD原稿ファイルのパス', max_length=512)),
                ('poster_image_file', models.CharField(blank=True, help_text='ポスター画像(poster.jpg)のパス', max_length=512)),
                ('sample_image_files', models.JSONField(blank=True, default=list, help_text='サンプル画像(01.jpg...)のパスリスト')),
                ('release_date', models.DateTimeField(blank=True, help_text='作品の配信開始日', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='DB登録日')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='DB最終更新日')),
            ],
            options={
                'verbose_name': '記事',
                'verbose_name_plural': '記事',
                'ordering': ['-release_date'],
            },
        ),
    ]
